theme: minima
title: Boomtastic
author: Merci24Dec
email: akashdubey24122707@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey everyone 👋, today I'm going to start with an awesome very basic and simple project using only HTML/CSS, JavaScript.
  Stay tuned everyone the content will be available shortly😉........

# social links
twitter_username: Merci99Dub # DO NOT include the @ character, or else the build will fail!
github_username:  Merci24Dec # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
